version: '3.8'
services:
  tron-monitor:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
      TRON_WALLET_ADDRESSES: "${TRON_WALLET_ADDRESSES}"
      CHECK_INTERVAL: "${CHECK_INTERVAL}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 64M